import type { H } from "../core/handler";
import { Podcast } from "../ai/podcast";
import { BlobStore } from "../core/blobstore";
import { fmt } from "./cards";
import { code, i, tgEscape } from "../tg/types";
import { kb } from "../tg/keyboards";

/**
 * Podcast surface: /podcast, playlist of past episodes, transcript view.
 * The audio itself is generated by src/ai/podcast.ts (script → TTS → R2).
 */
export async function podcastRoutes(h: H, scope: "daily" | "weekly" = "daily") {
  const fa = h.loc === "fa";
  await h.loading(fa ? "🎙 در حال تولید پادکست…" : "🎙 producing podcast…");

  const rows = await h.store.board("daily", "all", 6);
  const pod = new Podcast(h.env, h.ai, h.tg);

  // if there's a cached episode, send it immediately
  const day = new Date().toISOString().slice(0, 10);
  const blobs = new BlobStore(h.env);
  const cached = await blobs.head(`podcast/${scope}-${day}.mp3`);
  if (cached) {
    const obj = await blobs.get(`podcast/${scope}-${day}.mp3`);
    if (obj) {
      const buf = await obj.arrayBuffer();
      await h.tg.sendAudio(h.chatId, buf, `🎙 ${fa ? "پادکست" : "podcast"} ${scope} — ${day}`, {
        reply_markup: kb(
          [{ text: "📜 " + (fa ? "متن پادکست" : "Transcript"), cb: `p:text:${scope}` }],
          [{ text: "🔥 " + (fa ? "منابع امروز" : "Today's sources"), cb: "t:b:0,daily,all" }, { text: "🗓 " + (fa ? "هفتگی" : "Weekly"), cb: "p:weekly" }],
        ),
      });
      return;
    }
  }

  // otherwise build it now (this is the first-listener-pays model)
  const built = await pod.publish(rows, scope);
  if (!built) {
    return h.reply(`😕 ${fa ? "تولید پادکست ممکن نشد (سهمیه AI)." : "podcast generation unavailable."}`, kb([[{ text: "◀️", cb: "m:home" }]]), !!h.cbId);
  }
  if (!built.key) {
    return h.reply(
      `📜 <b>${fa ? "متن پادکست" : "Podcast script"}</b>\n<i>${fa ? "(سرویس صوتی در دسترس نبود — متن آماده است)" : "(TTS unavailable — script only)"}</i>\n\n` +
        tgEscape(built.script).slice(0, 3400),
      kb([[{ text: "🔁 " + (fa ? "دوباره" : "Retry"), cb: "p:today" }, { text: "◀️", cb: "m:home" }]]),
      !!h.cbId,
    );
  }
  const obj = await blobs.get(built.key);
  if (obj) {
    const buf = await obj.arrayBuffer();
    await h.tg.sendAudio(h.chatId, buf, `🎙 ${fa ? "پادکست تازه" : "fresh podcast"} — ${day}`, {
      reply_markup: kb(
        [{ text: "📜 " + (fa ? "متن" : "Transcript"), cb: `p:text:${scope}` }],
        [{ text: "🔥 " + (fa ? "داغ‌ترین‌ها" : "Trending"), cb: "t:b:0,daily,all" }],
      ),
    });
  }
  await h.reply(
    `🎙 <b>${fa ? "پادکست لنز" : "Lens podcast"}</b> ${scope === "daily" ? (fa ? "روزانه" : "daily") : (fa ? "هفتگی" : "weekly")}\n\n` +
      (fa ? "هر روز صبح، خلاصه صوتی پروژه‌های داغ گیت‌هاب — تولیدشده از داده زنده." : "A daily audio brief of trending repos."),
    kb(
      [{ text: "🗓 " + (fa ? "پادکست هفتگی" : "Weekly edition"), cb: "p:weekly" }],
      [{ text: "📊 " + (fa ? "نمودار رشد" : "Growth chart"), cb: "t:chart" }],
      [{ text: "◀️ " + (fa ? "منو" : "Menu"), cb: "m:home" }],
    ),
  );
}

/** Transcript viewer (text of the latest episode). */
export async function podcastText(h: H, scope: "daily" | "weekly" = "daily") {
  const fa = h.loc === "fa";
  const day = new Date().toISOString().slice(0, 10);
  const script = await new BlobStore(h.env).getText(`pod:script:${scope}-${day}`);
  if (!script) {
    const rows = await h.store.board("daily", "all", 6);
    const pod = new Podcast(h.env, h.ai, h.tg);
    const s = await pod.script(rows, scope);
    if (!s) return h.reply(fa ? "متنی تولید نشد." : "no script", kb([[{ text: "◀️", cb: "p:today" }]]), !!h.cbId);
    await new BlobStore(h.env).putText(`pod:script:${scope}-${day}`, s);
    return h.reply(`📜 <b>${fa ? "متن پادکست" : "Script"}</b>\n\n${tgEscape(s).slice(0, 3600)}`, kb([[{ text: "🎙 " + (fa ? "شنیدن" : "Listen"), cb: "p:today" }]]), !!h.cbId);
  }
  return h.reply(
    `📜 <b>${fa ? "متن پادکست" : "Script"}</b>\n\n${tgEscape(script).slice(0, 3600)}`,
    kb([[{ text: "🎙 " + (fa ? "شنیدن" : "Listen"), cb: "p:today" }], [{ text: "◀️ " + (fa ? "بازگشت" : "Back"), cb: "m:home" }]]),
    !!h.cbId,
  );
}
