#!/usr/bin/env node
/**
 * Embed schema/d1.sql into the worker.
 *
 * The one-click deploy creates a *brand new* D1 database in someone else's
 * account and has to put the tables in it. A worker cannot read a file from the
 * repository at runtime, and shipping the schema as a loose string would mean
 * maintaining the same DDL twice — so the file is the single source and this
 * turns it into a module at build time.
 *
 * Statements are split here rather than at runtime for the same reason sqlcheck
 * exists: semicolons inside string literals and `--` comments are exactly where
 * a naive `split(";")` produces a broken schema, and a broken schema in a
 * stranger's fresh database is the worst possible failure mode.
 *
 * Run by scripts/check.sh before tsc, so the generated file can never be stale.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const sql = readFileSync(join(root, "schema/d1.sql"), "utf8");

/** Remove `--` comments without touching them inside 'string literals'. */
function stripComments(s) {
  let out = "";
  let inStr = false;
  for (let i = 0; i < s.length; i++) {
    const c = s[i];
    if (inStr) {
      out += c;
      if (c === "'") {
        if (s[i + 1] === "'") { out += s[++i]; } else { inStr = false; }
      }
      continue;
    }
    if (c === "'") { inStr = true; out += c; continue; }
    if (c === "-" && s[i + 1] === "-") {
      while (i < s.length && s[i] !== "\n") i++;
      out += "\n";
      continue;
    }
    out += c;
  }
  return out;
}

/** Split on semicolons outside string literals. */
function splitStatements(s) {
  const out = [];
  let cur = "";
  let inStr = false;
  for (let i = 0; i < s.length; i++) {
    const c = s[i];
    if (inStr) {
      cur += c;
      if (c === "'") {
        if (s[i + 1] === "'") { cur += s[++i]; } else { inStr = false; }
      }
      continue;
    }
    if (c === "'") { inStr = true; cur += c; continue; }
    if (c === ";") {
      if (cur.trim()) out.push(cur.trim());
      cur = "";
      continue;
    }
    cur += c;
  }
  if (cur.trim()) out.push(cur.trim());
  return out;
}

const stmts = splitStatements(stripComments(sql))
  // a lone `BEGIN`/`COMMIT` around a batch is not a statement the API wants
  .filter((s) => !/^(BEGIN|COMMIT|PRAGMA\s+foreign_keys)/i.test(s));

// Guard rails: a generation that quietly produces two statements would create a
// database with no tables and look like a Cloudflare problem.
const creates = stmts.filter((s) => /^CREATE\s+TABLE/i.test(s)).length;
const indexes = stmts.filter((s) => /^CREATE\s+(UNIQUE\s+)?INDEX/i.test(s)).length;
if (creates < 30 || indexes < 20) {
  console.error(`gen-schema: suspicious split — ${creates} tables, ${indexes} indexes of ${stmts.length} statements`);
  process.exit(1);
}

const banner =
  "// GENERATED by scripts/gen-schema.mjs from schema/d1.sql — do not edit.\n" +
  "// Regenerated by scripts/check.sh, so it is never out of date with the file.\n";

const body =
  banner +
  `export const D1_STATEMENTS: string[] = [\n` +
  stmts.map((s) => "  " + JSON.stringify(s) + ",").join("\n") +
  `\n];\n\nexport const D1_SCHEMA_FINGERPRINT = ${JSON.stringify(
    stmts.length + ":" + creates + ":" + indexes,
  )};\n`;

mkdirSync(join(root, "src/hub"), { recursive: true });
writeFileSync(join(root, "src/hub/schema.gen.ts"), body);
console.log(`gen-schema: ${stmts.length} statements (${creates} tables, ${indexes} indexes) → src/hub/schema.gen.ts`);
